services:
  db-sttp:
    image: mariadb:10.4
    container_name: db-sttp
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME} 
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD} 
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
    networks:
      - strapi-network
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "${DATABASE_USERNAME}", "-p${DATABASE_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  strapi-sttp:
    container_name: strapi-sttp
    build: .
    networks:
      - strapi-network
    volumes:
      - uploads-strapi-sttp:/strapi-sttp/public/uploads
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -fs http://localhost:1337"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
    depends_on:
      db-sttp:
        condition: service_healthy
        
  rev-proxy-strapi:
    image: nginx:alpine
    container_name: rev-proxy-strapi
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4001:80"
    networks:
      - strapi-network
    depends_on:
      strapi-sttp:
        condition: service_healthy

networks:
  strapi-network:

volumes:
  uploads-strapi-sttp:
  dbdata: